"""MOCK orders for held-out v2 (taxonomy v3 eval). EVERYTHING HERE IS MOCK.

Generated by scripts/v3/heldout_v2_design.py BEFORE any v2 message was generated / labelled and before any
v3 pipeline run. Fresh order ids (TO-8xxxx) and customers, so held-out v2 never reuses dev orders."""

ORDERS_V2_RAW = [
 {
  "order_id": "TO-80001",
  "customer": "bram001@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80002",
  "customer": "carla002@example.test",
  "days_ago": 26,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80003",
  "customer": "dmitri003@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80004",
  "customer": "elena004@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80005",
  "customer": "farid005@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80006",
  "customer": "greta006@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80007",
  "customer": "hiro007@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80008",
  "customer": "ines008@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80009",
  "customer": "jonas009@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80010",
  "customer": "kenta010@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80011",
  "customer": "lucia011@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80012",
  "customer": "mei012@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80013",
  "customer": "nils013@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80014",
  "customer": "olga014@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80015",
  "customer": "pablo015@example.test",
  "days_ago": 18,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80016",
  "customer": "qing016@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80017",
  "customer": "rosa017@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80018",
  "customer": "sven018@example.test",
  "days_ago": 18,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80019",
  "customer": "tomoko019@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80020",
  "customer": "ugo020@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80021",
  "customer": "vera021@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 2,
    "logistics": {
     "status": "DELIVERED_PARTIAL",
     "carrier": "MockPost",
     "delivered_qty": 1
    }
   }
  ]
 },
 {
  "order_id": "TO-80022",
  "customer": "wei022@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80023",
  "customer": "xenia023@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 2,
    "logistics": {
     "status": "DELIVERED_PARTIAL",
     "carrier": "MockPost",
     "delivered_qty": 1
    }
   }
  ]
 },
 {
  "order_id": "TO-80024",
  "customer": "yusuf024@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80025",
  "customer": "zara025@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80026",
  "customer": "aiko026@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80027",
  "customer": "bram027@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80028",
  "customer": "carla028@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80029",
  "customer": "dmitri029@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80030",
  "customer": "elena030@example.test",
  "days_ago": 140,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80031",
  "customer": "farid031@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80032",
  "customer": "greta032@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80033",
  "customer": "hiro033@example.test",
  "days_ago": 95,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80034",
  "customer": "ines034@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80035",
  "customer": "jonas035@example.test",
  "days_ago": 600,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80036",
  "customer": "kenta036@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80037",
  "customer": "lucia037@example.test",
  "days_ago": 260,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80038",
  "customer": "mei038@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80039",
  "customer": "nils039@example.test",
  "days_ago": 400,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80040",
  "customer": "olga040@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80041",
  "customer": "pablo041@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80042",
  "customer": "qing042@example.test",
  "days_ago": 170,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80043",
  "customer": "rosa043@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80044",
  "customer": "sven044@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80045",
  "customer": "tomoko045@example.test",
  "days_ago": 140,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80046",
  "customer": "ugo046@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80047",
  "customer": "vera047@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80048",
  "customer": "wei048@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80049",
  "customer": "xenia049@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80050",
  "customer": "yusuf050@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80051",
  "customer": "zara051@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80052",
  "customer": "aiko052@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80053",
  "customer": "bram053@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80054",
  "customer": "carla054@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80055",
  "customer": "dmitri055@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80056",
  "customer": "elena056@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80057",
  "customer": "farid057@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80058",
  "customer": "greta058@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80059",
  "customer": "hiro059@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80060",
  "customer": "ines060@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80061",
  "customer": "jonas061@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80062",
  "customer": "kenta062@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80063",
  "customer": "lucia063@example.test",
  "days_ago": 160,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80064",
  "customer": "mei064@example.test",
  "days_ago": 160,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80065",
  "customer": "nils065@example.test",
  "days_ago": 160,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80066",
  "customer": "olga066@example.test",
  "days_ago": 160,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80067",
  "customer": "pablo067@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80068",
  "customer": "qing068@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80069",
  "customer": "rosa069@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80070",
  "customer": "sven070@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80071",
  "customer": "tomoko071@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80072",
  "customer": "ugo072@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80073",
  "customer": "vera073@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80074",
  "customer": "xenia075@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80075",
  "customer": "zara077@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80076",
  "customer": "greta084@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80077",
  "customer": "hiro085@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80078",
  "customer": "ines086@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80079",
  "customer": "jonas087@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80080",
  "customer": "kenta088@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80081",
  "customer": "lucia089@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80082",
  "customer": "mei090@example.test",
  "days_ago": 25,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80083",
  "customer": "nils091@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80084",
  "customer": "olga092@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80085",
  "customer": "pablo093@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80086",
  "customer": "qing094@example.test",
  "days_ago": 25,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80087",
  "customer": "rosa095@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80088",
  "customer": "sven096@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80089",
  "customer": "tomoko097@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80090",
  "customer": "ugo098@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80091",
  "customer": "vera099@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80092",
  "customer": "wei100@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80093",
  "customer": "xenia101@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80094",
  "customer": "yusuf102@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80095",
  "customer": "zara103@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80096",
  "customer": "aiko104@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80097",
  "customer": "bram105@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80098",
  "customer": "carla106@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80099",
  "customer": "dmitri107@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80100",
  "customer": "elena108@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80101",
  "customer": "farid109@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80102",
  "customer": "greta110@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80103",
  "customer": "hiro111@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80104",
  "customer": "ines112@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80105",
  "customer": "jonas113@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80106",
  "customer": "kenta114@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80107",
  "customer": "lucia115@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80108",
  "customer": "mei116@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80109",
  "customer": "nils117@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80110",
  "customer": "olga118@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80111",
  "customer": "pablo119@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80112",
  "customer": "qing120@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80113",
  "customer": "rosa121@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80114",
  "customer": "sven122@example.test",
  "days_ago": 27,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80115",
  "customer": "tomoko123@example.test",
  "days_ago": 17,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80116",
  "customer": "ugo124@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80117",
  "customer": "vera125@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80118",
  "customer": "wei126@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80119",
  "customer": "xenia127@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80120",
  "customer": "yusuf128@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80121",
  "customer": "zara129@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80122",
  "customer": "aiko130@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80123",
  "customer": "bram131@example.test",
  "days_ago": 75,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80124",
  "customer": "carla132@example.test",
  "days_ago": 75,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80125",
  "customer": "dmitri133@example.test",
  "days_ago": 75,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80126",
  "customer": "elena134@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80127",
  "customer": "farid135@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80128",
  "customer": "greta136@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80129",
  "customer": "hiro137@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80130",
  "customer": "ines138@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80131",
  "customer": "jonas139@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80132",
  "customer": "kenta140@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80133",
  "customer": "lucia141@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80134",
  "customer": "mei142@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80135",
  "customer": "nils143@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80136",
  "customer": "olga144@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80137",
  "customer": "pablo145@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80138",
  "customer": "qing146@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80139",
  "customer": "rosa147@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80140",
  "customer": "sven148@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80141",
  "customer": "tomoko149@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80142",
  "customer": "ugo150@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80143",
  "customer": "vera151@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80144",
  "customer": "wei152@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80145",
  "customer": "xenia153@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80146",
  "customer": "yusuf154@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80147",
  "customer": "zara155@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80148",
  "customer": "aiko156@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80149",
  "customer": "bram157@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80150",
  "customer": "carla158@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80151",
  "customer": "kenta166@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80152",
  "customer": "lucia167@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80153",
  "customer": "mei168@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80154",
  "customer": "nils169@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80155",
  "customer": "olga170@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80156",
  "customer": "pablo171@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80157",
  "customer": "qing172@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80158",
  "customer": "rosa173@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80159",
  "customer": "sven174@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80160",
  "customer": "tomoko175@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80161",
  "customer": "ugo176@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80162",
  "customer": "vera177@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80163",
  "customer": "wei178@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80164",
  "customer": "xenia179@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80165",
  "customer": "yusuf180@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80166",
  "customer": "zara181@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "eta_days": 2,
     "tracking": "MP555000111"
    }
   }
  ]
 },
 {
  "order_id": "TO-80167",
  "customer": "aiko182@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "eta_days": 2,
     "tracking": "MP555000111"
    }
   }
  ]
 },
 {
  "order_id": "TO-80168",
  "customer": "bram183@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "eta_days": 2,
     "tracking": "MP555000111"
    }
   }
  ]
 },
 {
  "order_id": "TO-80169",
  "customer": "carla184@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80170",
  "customer": "dmitri185@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80171",
  "customer": "elena186@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80172",
  "customer": "farid187@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80173",
  "customer": "greta188@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80174",
  "customer": "hiro189@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80175",
  "customer": "ines190@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80176",
  "customer": "jonas191@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80177",
  "customer": "kenta192@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80178",
  "customer": "lucia193@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80179",
  "customer": "mei194@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80180",
  "customer": "sven200@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80181",
  "customer": "tomoko201@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80182",
  "customer": "ugo202@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80183",
  "customer": "vera203@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80184",
  "customer": "wei204@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80185",
  "customer": "xenia205@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80186",
  "customer": "yusuf206@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80187",
  "customer": "zara207@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80188",
  "customer": "aiko208@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80189",
  "customer": "bram209@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80190",
  "customer": "carla210@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "L",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80191",
  "customer": "dmitri211@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80192",
  "customer": "elena212@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80193",
  "customer": "farid213@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80194",
  "customer": "greta214@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80195",
  "customer": "hiro215@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80196",
  "customer": "ines216@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80197",
  "customer": "jonas217@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80198",
  "customer": "kenta218@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80199",
  "customer": "lucia219@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80200",
  "customer": "mei220@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80201",
  "customer": "nils221@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80202",
  "customer": "olga222@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80203",
  "customer": "pablo223@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80204",
  "customer": "qing224@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80205",
  "customer": "rosa225@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80206",
  "customer": "sven226@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80207",
  "customer": "tomoko227@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80208",
  "customer": "ugo228@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80209",
  "customer": "vera229@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80210",
  "customer": "wei230@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80211",
  "customer": "xenia231@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80212",
  "customer": "yusuf232@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80213",
  "customer": "zara233@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80214",
  "customer": "aiko234@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80215",
  "customer": "bram235@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80216",
  "customer": "carla236@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80217",
  "customer": "dmitri237@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80218",
  "customer": "elena238@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80219",
  "customer": "farid239@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80220",
  "customer": "greta240@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80221",
  "customer": "hiro241@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "green",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80222",
  "customer": "ines242@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80223",
  "customer": "jonas243@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80224",
  "customer": "kenta244@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80225",
  "customer": "lucia245@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80226",
  "customer": "mei246@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80227",
  "customer": "nils247@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80228",
  "customer": "nils247@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80229",
  "customer": "olga248@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80230",
  "customer": "olga248@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80231",
  "customer": "pablo249@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80232",
  "customer": "pablo249@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80233",
  "customer": "qing250@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80234",
  "customer": "qing250@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80235",
  "customer": "rosa251@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80236",
  "customer": "rosa251@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80237",
  "customer": "sven252@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80238",
  "customer": "tomoko253@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80239",
  "customer": "ugo254@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80240",
  "customer": "vera255@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80241",
  "customer": "wei256@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80242",
  "customer": "xenia257@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80243",
  "customer": "yusuf258@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80244",
  "customer": "zara259@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80245",
  "customer": "aiko260@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80246",
  "customer": "bram261@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80247",
  "customer": "carla262@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80248",
  "customer": "dmitri263@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80249",
  "customer": "elena264@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80250",
  "customer": "farid265@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80251",
  "customer": "greta266@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80252",
  "customer": "hiro267@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80253",
  "customer": "ines268@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80254",
  "customer": "jonas269@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80255",
  "customer": "kenta270@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80256",
  "customer": "lucia271@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80257",
  "customer": "mei272@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80258",
  "customer": "nils273@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80259",
  "customer": "olga274@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80260",
  "customer": "pablo275@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80261",
  "customer": "qing276@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80262",
  "customer": "rosa277@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80263",
  "customer": "sven278@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80264",
  "customer": "tomoko279@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80265",
  "customer": "ugo280@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80266",
  "customer": "vera281@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80267",
  "customer": "wei282@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80268",
  "customer": "xenia283@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80269",
  "customer": "yusuf284@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80270",
  "customer": "zara285@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-80271",
  "customer": "aiko286@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 }
]
