"""MOCK orders for held-out v3 (v3.1 round). EVERYTHING HERE IS MOCK.

Generated by scripts/v3/heldout_v3_design.py BEFORE any v3 message was generated / labelled / run. Fresh ids TO-9xxxx."""

ORDERS_V3_RAW = [
 {
  "order_id": "TO-90001",
  "customer": "bea001@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90002",
  "customer": "chiara002@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90003",
  "customer": "diego003@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90004",
  "customer": "emma004@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90005",
  "customer": "fumiko005@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90006",
  "customer": "gonzalo006@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90007",
  "customer": "hanna007@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90008",
  "customer": "isamu008@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90009",
  "customer": "julia009@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90010",
  "customer": "kai010@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90011",
  "customer": "luis011@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90012",
  "customer": "mina012@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90013",
  "customer": "noah013@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90014",
  "customer": "oskar014@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90015",
  "customer": "paula015@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90016",
  "customer": "rin016@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90017",
  "customer": "sofia017@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90018",
  "customer": "taro018@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90019",
  "customer": "ulla019@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90020",
  "customer": "valeria020@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90021",
  "customer": "wen021@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90022",
  "customer": "yuki022@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90023",
  "customer": "zoe023@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90024",
  "customer": "akira024@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90025",
  "customer": "bea025@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90026",
  "customer": "chiara026@example.test",
  "days_ago": 18,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90027",
  "customer": "diego027@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90028",
  "customer": "emma028@example.test",
  "days_ago": 18,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90029",
  "customer": "fumiko029@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90030",
  "customer": "gonzalo030@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 2,
    "logistics": {
     "status": "DELIVERED_PARTIAL",
     "carrier": "MockPost",
     "delivered_qty": 1
    }
   }
  ]
 },
 {
  "order_id": "TO-90031",
  "customer": "hanna031@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90032",
  "customer": "isamu032@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90033",
  "customer": "julia033@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90034",
  "customer": "kai034@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90035",
  "customer": "luis035@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90036",
  "customer": "mina036@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 2,
    "logistics": {
     "status": "DELIVERED_PARTIAL",
     "carrier": "MockPost",
     "delivered_qty": 1
    }
   }
  ]
 },
 {
  "order_id": "TO-90037",
  "customer": "noah037@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90038",
  "customer": "oskar038@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90039",
  "customer": "paula039@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90040",
  "customer": "rin040@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90041",
  "customer": "sofia041@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90042",
  "customer": "taro042@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90043",
  "customer": "ulla043@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90044",
  "customer": "valeria044@example.test",
  "days_ago": 330,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90045",
  "customer": "wen045@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90046",
  "customer": "yuki046@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90047",
  "customer": "zoe047@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90048",
  "customer": "akira048@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90049",
  "customer": "bea049@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90050",
  "customer": "chiara050@example.test",
  "days_ago": 280,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90051",
  "customer": "diego051@example.test",
  "days_ago": 95,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90052",
  "customer": "emma052@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90053",
  "customer": "fumiko053@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90054",
  "customer": "gonzalo054@example.test",
  "days_ago": 400,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90055",
  "customer": "hanna055@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90056",
  "customer": "isamu056@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90057",
  "customer": "julia057@example.test",
  "days_ago": 400,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90058",
  "customer": "kai058@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90059",
  "customer": "luis059@example.test",
  "days_ago": 260,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90060",
  "customer": "mina060@example.test",
  "days_ago": 260,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90061",
  "customer": "noah061@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90062",
  "customer": "oskar062@example.test",
  "days_ago": 70,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90063",
  "customer": "paula063@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90064",
  "customer": "rin064@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90065",
  "customer": "sofia065@example.test",
  "days_ago": 45,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90066",
  "customer": "taro066@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90067",
  "customer": "ulla067@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90068",
  "customer": "valeria068@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90069",
  "customer": "wen069@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90070",
  "customer": "yuki070@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90071",
  "customer": "zoe071@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90072",
  "customer": "akira072@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90073",
  "customer": "bea073@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90074",
  "customer": "chiara074@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90075",
  "customer": "diego075@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90076",
  "customer": "emma076@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90077",
  "customer": "fumiko077@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90078",
  "customer": "gonzalo078@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90079",
  "customer": "hanna079@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90080",
  "customer": "isamu080@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90081",
  "customer": "julia081@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90082",
  "customer": "kai082@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90083",
  "customer": "luis083@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90084",
  "customer": "mina084@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90085",
  "customer": "noah085@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90086",
  "customer": "oskar086@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90087",
  "customer": "paula087@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90088",
  "customer": "rin088@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90089",
  "customer": "sofia089@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90090",
  "customer": "taro090@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90091",
  "customer": "ulla091@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90092",
  "customer": "valeria092@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90093",
  "customer": "wen093@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90094",
  "customer": "yuki094@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90095",
  "customer": "zoe095@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90096",
  "customer": "akira096@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90097",
  "customer": "bea097@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90098",
  "customer": "chiara098@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90099",
  "customer": "diego099@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90100",
  "customer": "emma100@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90101",
  "customer": "fumiko101@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90102",
  "customer": "gonzalo102@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90103",
  "customer": "hanna103@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90104",
  "customer": "isamu104@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90105",
  "customer": "julia105@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90106",
  "customer": "kai106@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90107",
  "customer": "luis107@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90108",
  "customer": "mina108@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90109",
  "customer": "noah109@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90110",
  "customer": "oskar110@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90111",
  "customer": "paula111@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90112",
  "customer": "rin112@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90113",
  "customer": "sofia113@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90114",
  "customer": "taro114@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90115",
  "customer": "ulla115@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90116",
  "customer": "valeria116@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90117",
  "customer": "wen117@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90118",
  "customer": "yuki118@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90119",
  "customer": "zoe119@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90120",
  "customer": "akira120@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90121",
  "customer": "bea121@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90122",
  "customer": "chiara122@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90123",
  "customer": "diego123@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90124",
  "customer": "emma124@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90125",
  "customer": "fumiko125@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90126",
  "customer": "gonzalo126@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90127",
  "customer": "hanna127@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90128",
  "customer": "isamu128@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90129",
  "customer": "julia129@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90130",
  "customer": "kai130@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90131",
  "customer": "luis131@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90132",
  "customer": "mina132@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90133",
  "customer": "noah133@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90134",
  "customer": "oskar134@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90135",
  "customer": "paula135@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90136",
  "customer": "rin136@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90137",
  "customer": "sofia137@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90138",
  "customer": "taro138@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90139",
  "customer": "ulla139@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90140",
  "customer": "valeria140@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90141",
  "customer": "wen141@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90142",
  "customer": "yuki142@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90143",
  "customer": "zoe143@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   },
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90144",
  "customer": "akira144@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90145",
  "customer": "bea145@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90146",
  "customer": "chiara146@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90147",
  "customer": "diego147@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90148",
  "customer": "emma148@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90149",
  "customer": "fumiko149@example.test",
  "days_ago": 250,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90150",
  "customer": "gonzalo150@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90151",
  "customer": "hanna151@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90152",
  "customer": "isamu152@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90153",
  "customer": "julia153@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90154",
  "customer": "kai154@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90155",
  "customer": "luis155@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90156",
  "customer": "mina156@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90157",
  "customer": "noah157@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90158",
  "customer": "oskar158@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90159",
  "customer": "paula159@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90160",
  "customer": "rin160@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90161",
  "customer": "sofia161@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90162",
  "customer": "taro162@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90163",
  "customer": "ulla163@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90164",
  "customer": "valeria164@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90165",
  "customer": "wen165@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90166",
  "customer": "yuki166@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90167",
  "customer": "zoe167@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90168",
  "customer": "akira168@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90169",
  "customer": "bea169@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90170",
  "customer": "chiara170@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90171",
  "customer": "diego171@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90172",
  "customer": "emma172@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90173",
  "customer": "fumiko173@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90174",
  "customer": "gonzalo174@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90175",
  "customer": "hanna175@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90176",
  "customer": "isamu176@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90177",
  "customer": "julia177@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90178",
  "customer": "kai178@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90179",
  "customer": "luis179@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90180",
  "customer": "mina180@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90181",
  "customer": "noah181@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90182",
  "customer": "oskar182@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90183",
  "customer": "paula183@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90184",
  "customer": "rin184@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90185",
  "customer": "sofia185@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90186",
  "customer": "taro186@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90187",
  "customer": "ulla187@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90188",
  "customer": "valeria188@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90189",
  "customer": "wen189@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90190",
  "customer": "yuki190@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90191",
  "customer": "zoe191@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90192",
  "customer": "akira192@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90193",
  "customer": "bea193@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90194",
  "customer": "chiara194@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90195",
  "customer": "diego195@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90196",
  "customer": "emma196@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90197",
  "customer": "fumiko197@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90198",
  "customer": "gonzalo198@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90199",
  "customer": "hanna199@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90200",
  "customer": "isamu200@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90201",
  "customer": "julia201@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90202",
  "customer": "kai202@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90203",
  "customer": "luis203@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90204",
  "customer": "mina204@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90205",
  "customer": "noah205@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90206",
  "customer": "oskar206@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90207",
  "customer": "paula207@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90208",
  "customer": "rin208@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90209",
  "customer": "sofia209@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90210",
  "customer": "taro210@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90211",
  "customer": "ulla211@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90212",
  "customer": "valeria212@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90213",
  "customer": "wen213@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90214",
  "customer": "yuki214@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90215",
  "customer": "zoe215@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90216",
  "customer": "akira216@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90217",
  "customer": "bea217@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90218",
  "customer": "chiara218@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90219",
  "customer": "diego219@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90220",
  "customer": "emma220@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90221",
  "customer": "fumiko221@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90222",
  "customer": "gonzalo222@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90223",
  "customer": "hanna223@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90224",
  "customer": "isamu224@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90225",
  "customer": "julia225@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90226",
  "customer": "kai226@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90227",
  "customer": "luis227@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90228",
  "customer": "mina228@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90229",
  "customer": "noah229@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90230",
  "customer": "oskar230@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90231",
  "customer": "paula231@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90232",
  "customer": "rin232@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90233",
  "customer": "sofia233@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90234",
  "customer": "taro234@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90235",
  "customer": "ulla235@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90236",
  "customer": "valeria236@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90237",
  "customer": "wen237@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90238",
  "customer": "yuki238@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90239",
  "customer": "zoe239@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90240",
  "customer": "akira240@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90241",
  "customer": "bea241@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90242",
  "customer": "chiara242@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90243",
  "customer": "diego243@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90244",
  "customer": "fumiko245@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90245",
  "customer": "kai250@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90246",
  "customer": "mina252@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90247",
  "customer": "noah253@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90248",
  "customer": "valeria260@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90249",
  "customer": "wen261@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90250",
  "customer": "yuki262@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90251",
  "customer": "zoe263@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90252",
  "customer": "akira264@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90253",
  "customer": "bea265@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90254",
  "customer": "chiara266@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90255",
  "customer": "diego267@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90256",
  "customer": "emma268@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90257",
  "customer": "fumiko269@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90258",
  "customer": "gonzalo270@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90259",
  "customer": "hanna271@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90260",
  "customer": "isamu272@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90261",
  "customer": "julia273@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90262",
  "customer": "kai274@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90263",
  "customer": "luis275@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90264",
  "customer": "mina276@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90265",
  "customer": "noah277@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90266",
  "customer": "oskar278@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90267",
  "customer": "paula279@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90268",
  "customer": "rin280@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90269",
  "customer": "sofia281@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90270",
  "customer": "taro282@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90271",
  "customer": "ulla283@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90272",
  "customer": "valeria284@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90273",
  "customer": "wen285@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90274",
  "customer": "yuki286@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90275",
  "customer": "zoe287@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90276",
  "customer": "akira288@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90277",
  "customer": "bea289@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90278",
  "customer": "chiara290@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90279",
  "customer": "diego291@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90280",
  "customer": "emma292@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90281",
  "customer": "fumiko293@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90282",
  "customer": "gonzalo294@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90283",
  "customer": "hanna295@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90284",
  "customer": "isamu296@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90285",
  "customer": "julia297@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-90286",
  "customer": "kai298@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-90287",
  "customer": "luis299@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-90288",
  "customer": "mina300@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-90289",
  "customer": "noah301@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90290",
  "customer": "oskar302@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90291",
  "customer": "paula303@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90292",
  "customer": "rin304@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90293",
  "customer": "sofia305@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90294",
  "customer": "taro306@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90295",
  "customer": "ulla307@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90296",
  "customer": "valeria308@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90297",
  "customer": "wen309@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90298",
  "customer": "yuki310@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90299",
  "customer": "zoe311@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90300",
  "customer": "akira312@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90301",
  "customer": "bea313@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90302",
  "customer": "chiara314@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90303",
  "customer": "diego315@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90304",
  "customer": "emma316@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90305",
  "customer": "gonzalo318@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90306",
  "customer": "isamu320@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90307",
  "customer": "kai322@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90308",
  "customer": "mina324@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90309",
  "customer": "noah325@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90310",
  "customer": "oskar326@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90311",
  "customer": "paula327@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-90312",
  "customer": "rin328@example.test",
  "days_ago": 500,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 }
]
