"""MOCK orders for held-out v4 (v3.2 round). EVERYTHING HERE IS MOCK.

Generated by scripts/v3/heldout_v3_design.py BEFORE any v4 message was generated / labelled / run. Fresh ids TO-96xxx."""

ORDERS_V4_RAW = [
 {
  "order_id": "TO-96001",
  "customer": "bea.v4001@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96002",
  "customer": "chiara.v4002@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96003",
  "customer": "diego.v4003@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96004",
  "customer": "emma.v4004@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96005",
  "customer": "fumiko.v4005@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96006",
  "customer": "gonzalo.v4006@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96007",
  "customer": "hanna.v4007@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96008",
  "customer": "isamu.v4008@example.test",
  "days_ago": 21,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96009",
  "customer": "julia.v4009@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96010",
  "customer": "kai.v4010@example.test",
  "days_ago": 14,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96011",
  "customer": "luis.v4011@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96012",
  "customer": "mina.v4012@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96013",
  "customer": "noah.v4013@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96014",
  "customer": "oskar.v4014@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96015",
  "customer": "paula.v4015@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96016",
  "customer": "rin.v4016@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96017",
  "customer": "sofia.v4017@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96018",
  "customer": "taro.v4018@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96019",
  "customer": "ulla.v4019@example.test",
  "days_ago": 11,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96020",
  "customer": "valeria.v4020@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96021",
  "customer": "wen.v4021@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96022",
  "customer": "yuki.v4022@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96023",
  "customer": "zoe.v4023@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96024",
  "customer": "akira.v4024@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96025",
  "customer": "bea.v4025@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96026",
  "customer": "chiara.v4026@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96027",
  "customer": "diego.v4027@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96028",
  "customer": "emma.v4028@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96029",
  "customer": "fumiko.v4029@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96030",
  "customer": "gonzalo.v4030@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96031",
  "customer": "hanna.v4031@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96032",
  "customer": "isamu.v4032@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96033",
  "customer": "julia.v4033@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96034",
  "customer": "kai.v4034@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96035",
  "customer": "luis.v4035@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96036",
  "customer": "mina.v4036@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96037",
  "customer": "noah.v4037@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96038",
  "customer": "oskar.v4038@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96039",
  "customer": "paula.v4039@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96040",
  "customer": "rin.v4040@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96041",
  "customer": "sofia.v4041@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96042",
  "customer": "taro.v4042@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96043",
  "customer": "ulla.v4043@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96044",
  "customer": "valeria.v4044@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96045",
  "customer": "wen.v4045@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96046",
  "customer": "yuki.v4046@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96047",
  "customer": "zoe.v4047@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96048",
  "customer": "akira.v4048@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96049",
  "customer": "bea.v4049@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96050",
  "customer": "chiara.v4050@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96051",
  "customer": "diego.v4051@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96052",
  "customer": "emma.v4052@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96053",
  "customer": "fumiko.v4053@example.test",
  "days_ago": 13,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96054",
  "customer": "gonzalo.v4054@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96055",
  "customer": "hanna.v4055@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96056",
  "customer": "isamu.v4056@example.test",
  "days_ago": 45,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96057",
  "customer": "julia.v4057@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96058",
  "customer": "kai.v4058@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96059",
  "customer": "luis.v4059@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96060",
  "customer": "mina.v4060@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96061",
  "customer": "noah.v4061@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96062",
  "customer": "oskar.v4062@example.test",
  "days_ago": 45,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96063",
  "customer": "paula.v4063@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96064",
  "customer": "rin.v4064@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96065",
  "customer": "sofia.v4065@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96066",
  "customer": "taro.v4066@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96067",
  "customer": "ulla.v4067@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "LOST",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96068",
  "customer": "valeria.v4068@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96069",
  "customer": "wen.v4069@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96070",
  "customer": "yuki.v4070@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96071",
  "customer": "zoe.v4071@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96072",
  "customer": "akira.v4072@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96073",
  "customer": "bea.v4073@example.test",
  "days_ago": 220,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96074",
  "customer": "chiara.v4074@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96075",
  "customer": "diego.v4075@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96076",
  "customer": "emma.v4076@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96077",
  "customer": "fumiko.v4077@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96078",
  "customer": "gonzalo.v4078@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96079",
  "customer": "hanna.v4079@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96080",
  "customer": "isamu.v4080@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96081",
  "customer": "julia.v4081@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96082",
  "customer": "kai.v4082@example.test",
  "days_ago": 180,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96083",
  "customer": "luis.v4083@example.test",
  "days_ago": 180,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96084",
  "customer": "mina.v4084@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96085",
  "customer": "noah.v4085@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96086",
  "customer": "oskar.v4086@example.test",
  "days_ago": 180,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96087",
  "customer": "paula.v4087@example.test",
  "days_ago": 180,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96088",
  "customer": "rin.v4088@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96089",
  "customer": "sofia.v4089@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96090",
  "customer": "taro.v4090@example.test",
  "days_ago": 80,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96091",
  "customer": "ulla.v4091@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96092",
  "customer": "valeria.v4092@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96093",
  "customer": "wen.v4093@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96094",
  "customer": "yuki.v4094@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96095",
  "customer": "zoe.v4095@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96096",
  "customer": "akira.v4096@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96097",
  "customer": "bea.v4097@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96098",
  "customer": "chiara.v4098@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96099",
  "customer": "diego.v4099@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96100",
  "customer": "emma.v4100@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96101",
  "customer": "fumiko.v4101@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96102",
  "customer": "gonzalo.v4102@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96103",
  "customer": "hanna.v4103@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96104",
  "customer": "isamu.v4104@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96105",
  "customer": "julia.v4105@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96106",
  "customer": "kai.v4106@example.test",
  "days_ago": 420,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96107",
  "customer": "luis.v4107@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96108",
  "customer": "mina.v4108@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96109",
  "customer": "noah.v4109@example.test",
  "days_ago": 300,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96110",
  "customer": "oskar.v4110@example.test",
  "days_ago": 50,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96111",
  "customer": "paula.v4111@example.test",
  "days_ago": 50,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96112",
  "customer": "rin.v4112@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96113",
  "customer": "sofia.v4113@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96114",
  "customer": "taro.v4114@example.test",
  "days_ago": 50,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96115",
  "customer": "ulla.v4115@example.test",
  "days_ago": 50,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96116",
  "customer": "valeria.v4116@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96117",
  "customer": "wen.v4117@example.test",
  "days_ago": 200,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96118",
  "customer": "yuki.v4118@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96119",
  "customer": "zoe.v4119@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96120",
  "customer": "akira.v4120@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96121",
  "customer": "bea.v4121@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96122",
  "customer": "chiara.v4122@example.test",
  "days_ago": 240,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96123",
  "customer": "diego.v4123@example.test",
  "days_ago": 240,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96124",
  "customer": "emma.v4124@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96125",
  "customer": "fumiko.v4125@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96126",
  "customer": "gonzalo.v4126@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96127",
  "customer": "hanna.v4127@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96128",
  "customer": "isamu.v4128@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96129",
  "customer": "julia.v4129@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96130",
  "customer": "kai.v4130@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96131",
  "customer": "luis.v4131@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96132",
  "customer": "mina.v4132@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96133",
  "customer": "noah.v4133@example.test",
  "days_ago": 40,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96134",
  "customer": "oskar.v4134@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96135",
  "customer": "paula.v4135@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "CAMP-STOVE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96136",
  "customer": "rin.v4136@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96137",
  "customer": "sofia.v4137@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96138",
  "customer": "taro.v4138@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96139",
  "customer": "ulla.v4139@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96140",
  "customer": "valeria.v4140@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96141",
  "customer": "wen.v4141@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96142",
  "customer": "yuki.v4142@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96143",
  "customer": "zoe.v4143@example.test",
  "days_ago": 90,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96144",
  "customer": "akira.v4144@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96145",
  "customer": "bea.v4145@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96146",
  "customer": "chiara.v4146@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96147",
  "customer": "diego.v4147@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96148",
  "customer": "noah.v4157@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96149",
  "customer": "oskar.v4158@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96150",
  "customer": "paula.v4159@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96151",
  "customer": "rin.v4160@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96152",
  "customer": "sofia.v4161@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96153",
  "customer": "taro.v4162@example.test",
  "days_ago": 100,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96154",
  "customer": "ulla.v4163@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96155",
  "customer": "valeria.v4164@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96156",
  "customer": "wen.v4165@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96157",
  "customer": "yuki.v4166@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96158",
  "customer": "zoe.v4167@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96159",
  "customer": "akira.v4168@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96160",
  "customer": "bea.v4169@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96161",
  "customer": "chiara.v4170@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96162",
  "customer": "diego.v4171@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96163",
  "customer": "emma.v4172@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96164",
  "customer": "fumiko.v4173@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96165",
  "customer": "gonzalo.v4174@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96166",
  "customer": "hanna.v4175@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96167",
  "customer": "isamu.v4176@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96168",
  "customer": "julia.v4177@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96169",
  "customer": "kai.v4178@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96170",
  "customer": "luis.v4179@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96171",
  "customer": "mina.v4180@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96172",
  "customer": "noah.v4181@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96173",
  "customer": "oskar.v4182@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96174",
  "customer": "paula.v4183@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96175",
  "customer": "rin.v4184@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96176",
  "customer": "sofia.v4185@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96177",
  "customer": "taro.v4186@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96178",
  "customer": "ulla.v4187@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96179",
  "customer": "valeria.v4188@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96180",
  "customer": "wen.v4189@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96181",
  "customer": "yuki.v4190@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96182",
  "customer": "zoe.v4191@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96183",
  "customer": "akira.v4192@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96184",
  "customer": "bea.v4193@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96185",
  "customer": "chiara.v4194@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96186",
  "customer": "diego.v4195@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96187",
  "customer": "emma.v4196@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96188",
  "customer": "fumiko.v4197@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96189",
  "customer": "gonzalo.v4198@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96190",
  "customer": "hanna.v4199@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96191",
  "customer": "isamu.v4200@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96192",
  "customer": "julia.v4201@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96193",
  "customer": "kai.v4202@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96194",
  "customer": "luis.v4203@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96195",
  "customer": "mina.v4204@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96196",
  "customer": "noah.v4205@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96197",
  "customer": "oskar.v4206@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96198",
  "customer": "paula.v4207@example.test",
  "days_ago": 5,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96199",
  "customer": "rin.v4208@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96200",
  "customer": "sofia.v4209@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96201",
  "customer": "taro.v4210@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96202",
  "customer": "ulla.v4211@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96203",
  "customer": "valeria.v4212@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "navy",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96204",
  "customer": "yuki.v4214@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96205",
  "customer": "akira.v4216@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96206",
  "customer": "chiara.v4218@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96207",
  "customer": "emma.v4220@example.test",
  "days_ago": 30,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96208",
  "customer": "fumiko.v4221@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96209",
  "customer": "gonzalo.v4222@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96210",
  "customer": "hanna.v4223@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96211",
  "customer": "isamu.v4224@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96212",
  "customer": "julia.v4225@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96213",
  "customer": "kai.v4226@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96214",
  "customer": "luis.v4227@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96215",
  "customer": "mina.v4228@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96216",
  "customer": "noah.v4229@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96217",
  "customer": "oskar.v4230@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96218",
  "customer": "paula.v4231@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96219",
  "customer": "rin.v4232@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96220",
  "customer": "sofia.v4233@example.test",
  "days_ago": 15,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96221",
  "customer": "taro.v4234@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96222",
  "customer": "ulla.v4235@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96223",
  "customer": "valeria.v4236@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96224",
  "customer": "wen.v4237@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96225",
  "customer": "yuki.v4238@example.test",
  "days_ago": 20,
  "lines": [
   {
    "sku": "BACKPACK-30L",
    "variant": "black",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96226",
  "customer": "emma.v4244@example.test",
  "days_ago": 150,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96227",
  "customer": "mina.v4252@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96228",
  "customer": "noah.v4253@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96229",
  "customer": "oskar.v4254@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96230",
  "customer": "paula.v4255@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96231",
  "customer": "rin.v4256@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96232",
  "customer": "sofia.v4257@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96233",
  "customer": "taro.v4258@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96234",
  "customer": "ulla.v4259@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96235",
  "customer": "valeria.v4260@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96236",
  "customer": "wen.v4261@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96237",
  "customer": "yuki.v4262@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96238",
  "customer": "zoe.v4263@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96239",
  "customer": "akira.v4264@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96240",
  "customer": "bea.v4265@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96241",
  "customer": "chiara.v4266@example.test",
  "days_ago": 8,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "S",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96242",
  "customer": "diego.v4267@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96243",
  "customer": "emma.v4268@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96244",
  "customer": "fumiko.v4269@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96245",
  "customer": "gonzalo.v4270@example.test",
  "days_ago": 6,
  "lines": [
   {
    "sku": "SALE-SOCKS",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96246",
  "customer": "hanna.v4271@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-96247",
  "customer": "isamu.v4272@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-96248",
  "customer": "julia.v4273@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-96249",
  "customer": "kai.v4274@example.test",
  "days_ago": 3,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "44",
    "qty": 1,
    "logistics": {
     "status": "IN_TRANSIT",
     "carrier": "MockPost",
     "tracking": "MP99887766"
    }
   }
  ]
 },
 {
  "order_id": "TO-96250",
  "customer": "luis.v4275@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96251",
  "customer": "mina.v4276@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96252",
  "customer": "noah.v4277@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96253",
  "customer": "oskar.v4278@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96254",
  "customer": "paula.v4279@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96255",
  "customer": "rin.v4280@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96256",
  "customer": "sofia.v4281@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96257",
  "customer": "taro.v4282@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96258",
  "customer": "ulla.v4283@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96259",
  "customer": "valeria.v4284@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96260",
  "customer": "wen.v4285@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96261",
  "customer": "yuki.v4286@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96262",
  "customer": "zoe.v4287@example.test",
  "days_ago": 12,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96263",
  "customer": "akira.v4288@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96264",
  "customer": "bea.v4289@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96265",
  "customer": "chiara.v4290@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96266",
  "customer": "diego.v4291@example.test",
  "days_ago": 10,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96267",
  "customer": "emma.v4292@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96268",
  "customer": "fumiko.v4293@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "DESK-LAMP",
    "variant": "white",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96269",
  "customer": "gonzalo.v4294@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96270",
  "customer": "hanna.v4295@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96271",
  "customer": "isamu.v4296@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96272",
  "customer": "julia.v4297@example.test",
  "days_ago": 9,
  "lines": [
   {
    "sku": "BREW-KETTLE",
    "variant": "standard",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96273",
  "customer": "kai.v4298@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96274",
  "customer": "luis.v4299@example.test",
  "days_ago": 60,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "41",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96275",
  "customer": "mina.v4300@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96276",
  "customer": "noah.v4301@example.test",
  "days_ago": 120,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "40",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96277",
  "customer": "oskar.v4302@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96278",
  "customer": "paula.v4303@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "39",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96279",
  "customer": "rin.v4304@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "43",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96280",
  "customer": "sofia.v4305@example.test",
  "days_ago": 7,
  "lines": [
   {
    "sku": "TRAIL-RUNNER-42",
    "variant": "42",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96281",
  "customer": "taro.v4306@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96282",
  "customer": "ulla.v4307@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96283",
  "customer": "valeria.v4308@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 },
 {
  "order_id": "TO-96284",
  "customer": "wen.v4309@example.test",
  "days_ago": 4,
  "lines": [
   {
    "sku": "CITY-JACKET",
    "variant": "M",
    "qty": 1,
    "logistics": {
     "status": "DELIVERED",
     "carrier": "MockPost"
    }
   }
  ]
 }
]
